/** Country → language options for the AI manager chat translator. */
export type LanguageOption = { code: string; label: string; language: string };

export const LANGUAGES: LanguageOption[] = [
  { code: "en", label: "🇬🇧 United Kingdom / USA — English", language: "English" },
  { code: "ne", label: "🇳🇵 Nepal — Nepali", language: "Nepali" },
  { code: "hi", label: "🇮🇳 India — Hindi", language: "Hindi" },
  { code: "bn", label: "🇧🇩 Bangladesh — Bengali", language: "Bengali" },
  { code: "ur", label: "🇵🇰 Pakistan — Urdu", language: "Urdu" },
  { code: "si", label: "🇱🇰 Sri Lanka — Sinhala", language: "Sinhala" },
  { code: "dz", label: "🇧🇹 Bhutan — Dzongkha", language: "Dzongkha" },
  { code: "zh", label: "🇨🇳 China — Chinese (Simplified)", language: "Simplified Chinese" },
  { code: "zh-TW", label: "🇹🇼 Taiwan — Chinese (Traditional)", language: "Traditional Chinese" },
  { code: "ja", label: "🇯🇵 Japan — Japanese", language: "Japanese" },
  { code: "ko", label: "🇰🇷 South Korea — Korean", language: "Korean" },
  { code: "th", label: "🇹🇭 Thailand — Thai", language: "Thai" },
  { code: "vi", label: "🇻🇳 Vietnam — Vietnamese", language: "Vietnamese" },
  { code: "id", label: "🇮🇩 Indonesia — Indonesian", language: "Indonesian" },
  { code: "ms", label: "🇲🇾 Malaysia — Malay", language: "Malay" },
  { code: "tl", label: "🇵🇭 Philippines — Filipino", language: "Filipino" },
  { code: "my", label: "🇲🇲 Myanmar — Burmese", language: "Burmese" },
  { code: "km", label: "🇰🇭 Cambodia — Khmer", language: "Khmer" },
  { code: "lo", label: "🇱🇦 Laos — Lao", language: "Lao" },
  { code: "mn", label: "🇲🇳 Mongolia — Mongolian", language: "Mongolian" },
  { code: "ar", label: "🇸🇦 Saudi Arabia / UAE — Arabic", language: "Arabic" },
  { code: "he", label: "🇮🇱 Israel — Hebrew", language: "Hebrew" },
  { code: "fa", label: "🇮🇷 Iran — Persian", language: "Persian" },
  { code: "tr", label: "🇹🇷 Türkiye — Turkish", language: "Turkish" },
  { code: "ru", label: "🇷🇺 Russia — Russian", language: "Russian" },
  { code: "uk", label: "🇺🇦 Ukraine — Ukrainian", language: "Ukrainian" },
  { code: "pl", label: "🇵🇱 Poland — Polish", language: "Polish" },
  { code: "cs", label: "🇨🇿 Czechia — Czech", language: "Czech" },
  { code: "sk", label: "🇸🇰 Slovakia — Slovak", language: "Slovak" },
  { code: "hu", label: "🇭🇺 Hungary — Hungarian", language: "Hungarian" },
  { code: "ro", label: "🇷🇴 Romania — Romanian", language: "Romanian" },
  { code: "bg", label: "🇧🇬 Bulgaria — Bulgarian", language: "Bulgarian" },
  { code: "el", label: "🇬🇷 Greece — Greek", language: "Greek" },
  { code: "de", label: "🇩🇪 Germany — German", language: "German" },
  { code: "fr", label: "🇫🇷 France — French", language: "French" },
  { code: "es", label: "🇪🇸 Spain — Spanish", language: "Spanish" },
  { code: "pt", label: "🇵🇹 Portugal — Portuguese", language: "European Portuguese" },
  { code: "pt-BR", label: "🇧🇷 Brazil — Portuguese", language: "Brazilian Portuguese" },
  { code: "it", label: "🇮🇹 Italy — Italian", language: "Italian" },
  { code: "nl", label: "🇳🇱 Netherlands — Dutch", language: "Dutch" },
  { code: "sv", label: "🇸🇪 Sweden — Swedish", language: "Swedish" },
  { code: "no", label: "🇳🇴 Norway — Norwegian", language: "Norwegian" },
  { code: "da", label: "🇩🇰 Denmark — Danish", language: "Danish" },
  { code: "fi", label: "🇫🇮 Finland — Finnish", language: "Finnish" },
  { code: "is", label: "🇮🇸 Iceland — Icelandic", language: "Icelandic" },
  { code: "sw", label: "🇰🇪 Kenya / Tanzania — Swahili", language: "Swahili" },
  { code: "am", label: "🇪🇹 Ethiopia — Amharic", language: "Amharic" },
  { code: "ha", label: "🇳🇬 Nigeria — Hausa", language: "Hausa" },
  { code: "af", label: "🇿🇦 South Africa — Afrikaans", language: "Afrikaans" },
  { code: "zu", label: "🇿🇦 South Africa — Zulu", language: "Zulu" },
];