/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as AuthenticatedAiManagerRouteImport } from './routes/_authenticated/ai-manager'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGuestChatsRouteImport } from './routes/_authenticated/guest-chats'
import { Route as AuthenticatedHousekeepingRouteImport } from './routes/_authenticated/housekeeping'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiManagerRoute = AuthenticatedAiManagerRouteImport.update({
  id: '/ai-manager',
  path: '/ai-manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuestChatsRoute = AuthenticatedGuestChatsRouteImport.update({
  id: '/guest-chats',
  path: '/guest-chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHousekeepingRoute =
  AuthenticatedHousekeepingRouteImport.update({
    id: '/housekeeping',
    path: '/housekeeping',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/concierge': typeof ConciergeRoute
  '/ai-manager': typeof AuthenticatedAiManagerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guest-chats': typeof AuthenticatedGuestChatsRoute
  '/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/concierge': typeof ConciergeRoute
  '/ai-manager': typeof AuthenticatedAiManagerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guest-chats': typeof AuthenticatedGuestChatsRoute
  '/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/concierge': typeof ConciergeRoute
  '/_authenticated/ai-manager': typeof AuthenticatedAiManagerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/guest-chats': typeof AuthenticatedGuestChatsRoute
  '/_authenticated/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/concierge'
    | '/ai-manager'
    | '/dashboard'
    | '/guest-chats'
    | '/housekeeping'
    | '/reservations'
    | '/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/concierge'
    | '/ai-manager'
    | '/dashboard'
    | '/guest-chats'
    | '/housekeeping'
    | '/reservations'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/concierge'
    | '/_authenticated/ai-manager'
    | '/_authenticated/dashboard'
    | '/_authenticated/guest-chats'
    | '/_authenticated/housekeeping'
    | '/_authenticated/reservations'
    | '/_authenticated/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConciergeRoute: typeof ConciergeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-manager': {
      id: '/_authenticated/ai-manager'
      path: '/ai-manager'
      fullPath: '/ai-manager'
      preLoaderRoute: typeof AuthenticatedAiManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guest-chats': {
      id: '/_authenticated/guest-chats'
      path: '/guest-chats'
      fullPath: '/guest-chats'
      preLoaderRoute: typeof AuthenticatedGuestChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/housekeeping': {
      id: '/_authenticated/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof AuthenticatedHousekeepingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiManagerRoute: typeof AuthenticatedAiManagerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGuestChatsRoute: typeof AuthenticatedGuestChatsRoute
  AuthenticatedHousekeepingRoute: typeof AuthenticatedHousekeepingRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiManagerRoute: AuthenticatedAiManagerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGuestChatsRoute: AuthenticatedGuestChatsRoute,
  AuthenticatedHousekeepingRoute: AuthenticatedHousekeepingRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConciergeRoute: ConciergeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
